#
# Makefile for Svelte app
#
usage:
	@echo "usage: make [install|build|run|web]"

install i:
	npm install

build b:
	npm run build
	
run r: run-start

run-dev rd:
	npm run dev

run-start rs:
	npm run start

run-start-dev rsd:
	npm run start dev

web w:
	open http://localhost:5000
