#
# Makefile for Svelte Tooling
#
usage:
	@echo "usage: [install]"

install i:
	npm install --global rollup
	npm install --save-dev svelte rollup-plugin-svelte
	npm install -g now
	npm install -g surge
	